GET http://localhost:8000/api/persons
###

GET http://localhost:8000/api/persons/4
###

GET http://localhost:8000/api/persons/5
###

DELETE http://localhost:8000/api/persons/5
###

POST  http://localhost:8000/api/persons
Content-Type: application/json

{
  "phoneNumber": "123",
  "name": "Daaaan"
}
###

POST  http://localhost:8000/api/persons
Content-Type: application/json

{
  "name": "Dan"
}
###

